FROM nginx:latest
ENV DEVOPS=mikhailyesman
RUN echo "<!doctype html><html lang="en"> <head> <meta charset="utf-8">  <title>Docker Nginx</title> </head> <body> <h2>$DEVOPS from Nginx container</h2> </body> </html>" > /usr/share/nginx/html/index.html
