---
- name: Install
  hosts: localhost
  become: True

  tasks:
    - name: Install Zabbix Agent
      yum: name="http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-agent-5.0.0-1.el8.x86_64.rpm"
    - name: IP
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        replace: 'Server=192.168.10.44'
        backup: yes

    - name: Start Agent
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '# StartAgents=3'
        replace: 'StartAgents=5'
        backup: yes

    - name: start zabbix-agent
      service: name=zabbix-agent state=started enabled=yes

    - name: firewall
      systemd:
            name: firewalld
            state: reloaded
