
version: '3.1'

services:
  db:
    image: mysql:5.7

    container_name: "mysql_task"

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: smes
      MYSQL_DATABASE: db_group
      MYSQL_USER: smes
      MYSQL_PASSWORD: smes
      USERNAME: Yesman Mikhail Mihajlovich
    ports:
      - 3308:3306
      - 33081:33061
      - 33080:33060
    volumes:
      - /opt/mysql/mysql_db:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8091:80
    environment:
      - PMA_ARBITRARY=1
